2020-11-09 12:32:52,054 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/biswa/Desktop/Almabase/app.py", line 65, in home
    session.clear()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/sessions.py", line 102, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2020-11-09 12:32:52,067 app          INFO     client -  
2020-11-09 12:32:52,067 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
2020-11-09 12:32:52,067 app          WARNING  user accessed - http://127.0.0.1:5000/
2020-11-09 12:33:59,292 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/biswa/Desktop/Almabase/app.py", line 65, in home
    session.clear()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/sessions.py", line 102, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2020-11-09 12:33:59,301 app          INFO     client -  
2020-11-09 12:33:59,301 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
2020-11-09 12:33:59,302 app          WARNING  user accessed - http://127.0.0.1:5000/
2020-11-09 12:34:18,167 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/biswa/Desktop/Almabase/app.py", line 65, in home
    session.clear()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/sessions.py", line 102, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2020-11-09 12:34:18,175 app          INFO     client -  
2020-11-09 12:34:18,175 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
2020-11-09 12:34:18,176 app          WARNING  user accessed - http://127.0.0.1:5000/
2020-11-09 12:35:12,283 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/biswa/Desktop/Almabase/app.py", line 65, in home
    session.clear()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/sessions.py", line 102, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2020-11-09 12:35:12,290 app          INFO     client -  
2020-11-09 12:35:12,290 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
2020-11-09 12:35:12,290 app          WARNING  user accessed - http://127.0.0.1:5000/
2020-11-09 12:35:17,424 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/biswa/Desktop/Almabase/app.py", line 65, in home
    session.clear()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/sessions.py", line 102, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2020-11-09 12:35:17,425 app          INFO     client -  
2020-11-09 12:35:17,425 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
2020-11-09 12:35:17,425 app          WARNING  user accessed - http://127.0.0.1:5000/
2020-11-09 12:35:35,867 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/biswa/Desktop/Almabase/app.py", line 65, in home
    session.clear()
  File "/Users/biswa/Desktop/Almabase/venv/lib/python3.8/site-packages/flask/sessions.py", line 102, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2020-11-09 12:35:35,876 app          INFO     client -  
2020-11-09 12:35:35,876 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
2020-11-09 12:35:35,877 app          WARNING  user accessed - http://127.0.0.1:5000/
2020-11-09 12:37:48,528 app          INFO     client - 
2020-11-09 12:37:48,529 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
2020-11-09 12:38:23,782 app          INFO     client - 
2020-11-09 12:38:23,783 app          INFO     user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
